= S3 for Kotlin

image:https://img.shields.io/badge/jvm-1.8-blue[title="Compatible with JVM 1.8"]
image:https://img.shields.io/badge/docs-javadoc-brightgreen[link="https://veupathdb.github.io/lib-s34k/javadoc"]
image:https://img.shields.io/badge/docs-dokka-brightgreen[link="https://veupathdb.github.io/lib-s34k/dokka"]



== Roadmap

v0.1.0::
Initial release.
+
Provides basic functionality over the S3 API.  In addition to:
+
--
* Targeted object/bucket tag deletions.
* Recursive bucket deletion
--
+
Does not include complex configuration of SSL, permissions, etc..
+
Does not include separate headers for multi-stage actions, such as recursive
tag deletion.
+
See the docs linked above for more information on what features are provided.
+
TODOs:
+
* [ ] https://github.com/VEuPathDB/lib-s34k/issues/1

v0.2.0::
TODOs:
+
--
* [x] Configuration of multi-stage recursive bucket deletion.
* [ ] Configuration of multi-stage targeted object tag deleteion.
* [ ] Configuration of multi-stage targeted bucket tag deletion.
* [ ] Version ID on object tag deletion params
* [ ] Recursive object deletes
* [ ] Configurable list operation page sizes
--