= S3 for Kotlin
:source-highlighter: highlightjs

image:https://img.shields.io/badge/jvm-1.8-blue[title="Compatible with JVM 1.8"]
image:https://img.shields.io/badge/docs-javadoc-brightgreen[link="https://veupathdb.github.io/lib-s34k/javadoc"]
image:https://img.shields.io/badge/docs-dokka-brightgreen[link="https://veupathdb.github.io/lib-s34k/dokka"]


== Usage

S34K defines the base API for a generalized abstraction layer over S3 API
clients and SDKs.  This project simply defines a standard API and does not
provide any functionality on its own.

Usage of this API is done through specific implementations (such as
https://github.com/VEuPathDB/lib-s34k-minio[S34K-Minio]).

=== Examples

.Getting an `S3Client` instance
[source, kotlin]
----
fun main() {
  val client = S3Api.newClient(S3Config(
    url       = "my-s3-host",
    accessKey = System.getenv("S3_ACCESS_KEY"),
    secretKey = System.getenv("S3_SECRET_KEY"),
  ))
}
----

.Upserting a bucket
[source, kotlin]
----
fun main() {
  val client = S3Api.newClient(...)

  // Simple call
  val bucket1 = client.createBucketIfNotExists("my-bucket-1")

  // Customized call
  val bucket2 = client.createBucketIfNotExists {
    bucketName = "my-bucket-2"
    headers.add("x-my-custom-header", "some value")
    tags.add("some-tag", "some tag value")
  }
}
----

.Uploading a file
[source, kotlin]
----
fun main() {
  val client = S3Api.newClient(...)
  val bucket = client.getBucket("my-bucket")

  // Simple call
  bucket.uploadFile("my/object/key", File("/path/to/some/local/file"))

  // Customized call
  bucket.uploadFile {
    path      = "my/object/key2"
    localFile = File("/path/to/some/file")
    partSize  = 26_214_400 // 25MiB
    tags.add(
      "foo"  to "bar",
      "fizz" to "buzz",
    )
  }
}
----


== Operations

The following operations are currently supported as of `v0.1.0`

=== Client

General bucket operations:

* Create bucket
* Create bucket if not exists
* Test bucket existence
* List buckets
* Delete bucket
* Delete bucket recursive


=== Bucket

Bucket specific and general object operations.

.Bucket operations:
* Delete
* Delete recursive
* Delete tags (all)
* Delete tags (targeted)
* Get tags
* Put tags

.Object operations:
* Delete single
* Delete bulk
* Delete tags
* Download
* Existence test
* Get
* Get tags
* List
* Put
* Put tags
* Put 'directory'
* Stat
* Touch
* Upload

=== Object

Object specific operations.

.Operations
* Exists test
* Delete
* Stat
* Get Tags
* Put Tags
* Delete Tags (all)
* Delete Tags (targeted)

== Roadmap

v0.1.0::
Initial release.
+
Provides basic functionality over the S3 API.  In addition to:
+
--
* Targeted object/bucket tag deletions.
* Recursive bucket deletion
--
+
Does not include complex configuration of SSL, permissions, etc..
+
Does not include separate headers for multi-stage actions, such as recursive
tag deletion.
+
See the docs linked above for more information on what features are provided.
+
TODOs:
+
* [ ] https://github.com/VEuPathDB/lib-s34k/issues/1

v0.2.0::
TODOs:
+
--
* [x] Configuration of multi-stage recursive bucket deletion.
* [ ] Configuration of multi-stage targeted object tag deletion.
* [ ] Configuration of multi-stage targeted bucket tag deletion.
* [ ] Version ID on object tag deletion params
* [ ] Recursive object deletes
* [ ] Configurable list operation page sizes
* [ ] Add callback to recursive bucket delete (all phases or just full op?)
* [ ] Rename default region to region (it's a normal property)
* [ ] Include cascading region value fetching (params || bucket || client)
--
